#
#
#build:
# docker build -t hoeggsoftware/jenkins-slave .
#
#run:
#	docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/bin/docker hoeggsoftware/jenkins-slave -url http:${GITHUB_USER}:${GITUB_TOKEN}@${JENKINS_SERVER}
